### ISSUE TITLE
Quantize functions can break with always open midi editor

### ISSUE THREAD

**Issue by kamakiri** [StephanRoemer/ReaScripts#1]
Hi Stephan

I'm using a setup where my midi editor remains open at all times. This means that I can have a take visible in the editor, even though no media item is selected in arrange view. In that case the different quantize functions fail with an error.

If you add something like this just after ``MIDIEditor = reaper.MIDIEditor_GetActive()`` in ``sr_Human quantize notes function.lua`` and ``sr_Quantize notes function.lua``: 

``if reaper.CountSelectedMediaItems(0) == 0 then 
   reaper.SetMediaItemSelected(reaper.GetMediaItemTake_Item(reaper.MIDIEditor_GetTake(MIDIEditor)), true)
end``

it will work even with no media item selected.

Thanks for your great work!

**Comment by StephanRoemer** [comment]
Thanks kamakiri!

Insanely busy at the moment, but I will definitely incorporate this.
While working I found some other issues with the script. Somehow, the notes are not quantized to the grid. Have to investigate that as well, as soon as I got some time.

**Comment by StephanRoemer** [comment]
Fixed!

**Comment by kamakiri** [comment]
Awesome Stephan - thank you!

Med venlig hilsen / best regards

Rasmus Hartvig  |  Atom Studio
rasmus@atoms.dk  | http://www.rasmushartvig.com/
--
